name: Frontend CI/CD (Validación y Despliegue)

on:
  push:
    branches:
      - master
      - main
      - feature/frontend-ui
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalar dependencias limpias
      run: npm ci

    - name: Construir proyecto Angular (Static Prerender)
      run: npm run build

    - name: Configurar Entorno de Páginas
      uses: actions/configure-pages@v4

    - name: Subir Artefacto de Producción
      uses: actions/upload-pages-artifact@v3
      with:
        # Apunta directamente a la carpeta de salida en tu raíz actual
        path: dist/meat-and-grill-frontend/browser

    - name: Desplegar en GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4