--
-- PostgreSQL database dump
--

-- \restrict u3VVYyrS4te058acgXPbTWSv79geuZi5IQFtmwpjo3hCfce8kt8Vp1bYP5lFMcj

-- Dumped from database version 17.10 (Debian 17.10-0+deb13u1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: agregados; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.agregados (
    id_agregado bigint NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    id_insumo bigint NOT NULL
);


ALTER TABLE public.agregados OWNER TO beckamdev;

--
-- Name: agregados_id_agregado_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.agregados ALTER COLUMN id_agregado ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agregados_id_agregado_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agregados_selected; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.agregados_selected (
    id_agregado_selected bigint NOT NULL,
    price numeric(38,2) NOT NULL,
    quantity integer NOT NULL,
    id_agregado bigint NOT NULL,
    id_plato_selected bigint NOT NULL
);


ALTER TABLE public.agregados_selected OWNER TO beckamdev;

--
-- Name: agregados_selected_id_agregado_selected_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.agregados_selected ALTER COLUMN id_agregado_selected ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agregados_selected_id_agregado_selected_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bebidas; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.bebidas (
    id_bebida bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.bebidas OWNER TO beckamdev;

--
-- Name: bebidas_id_bebida_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.bebidas ALTER COLUMN id_bebida ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bebidas_id_bebida_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bebidas_options; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.bebidas_options (
    id_bebida_option bigint NOT NULL,
    unit_price numeric(38,2) NOT NULL,
    id_bebida bigint NOT NULL,
    id_bebida_size bigint NOT NULL
);


ALTER TABLE public.bebidas_options OWNER TO beckamdev;

--
-- Name: bebidas_options_id_bebida_option_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.bebidas_options ALTER COLUMN id_bebida_option ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bebidas_options_id_bebida_option_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bebidas_selected; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.bebidas_selected (
    id_bebida_selected bigint NOT NULL,
    quantity integer NOT NULL,
    status character varying(255),
    subtotal numeric(38,2),
    id_bebida_option bigint,
    id_order bigint,
    CONSTRAINT bebidas_selected_status_check CHECK (((status)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADO'::character varying, 'EN_MESA'::character varying, 'ENTREGADO'::character varying])::text[])))
);


ALTER TABLE public.bebidas_selected OWNER TO beckamdev;

--
-- Name: bebidas_selected_id_bebida_selected_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.bebidas_selected ALTER COLUMN id_bebida_selected ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bebidas_selected_id_bebida_selected_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bebidas_sizes; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.bebidas_sizes (
    id_bebida_size bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.bebidas_sizes OWNER TO beckamdev;

--
-- Name: bebidas_sizes_id_bebida_size_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.bebidas_sizes ALTER COLUMN id_bebida_size ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bebidas_sizes_id_bebida_size_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cash_sessions; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.cash_sessions (
    id_session bigint NOT NULL,
    closed_at timestamp(6) without time zone,
    closing_cash numeric(38,2),
    opened_at timestamp(6) without time zone NOT NULL,
    opening_cash numeric(38,2),
    status character varying(255) NOT NULL,
    work_date smallint NOT NULL,
    id_employee bigint,
    id_week bigint NOT NULL,
    CONSTRAINT cash_sessions_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'CLOSED'::character varying])::text[]))),
    CONSTRAINT cash_sessions_work_date_check CHECK (((work_date >= 0) AND (work_date <= 6)))
);


ALTER TABLE public.cash_sessions OWNER TO beckamdev;

--
-- Name: cash_sessions_id_session_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.cash_sessions ALTER COLUMN id_session ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cash_sessions_id_session_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.employees (
    id_employee bigint NOT NULL,
    dni character varying(15) NOT NULL,
    last_name character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone_number character varying(11)
);


ALTER TABLE public.employees OWNER TO beckamdev;

--
-- Name: employees_id_employee_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.employees ALTER COLUMN id_employee ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_employee_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guarniciones; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.guarniciones (
    id_guarnicion bigint NOT NULL,
    group_name character varying(255) NOT NULL,
    CONSTRAINT guarniciones_group_name_check CHECK (((group_name)::text = ANY ((ARRAY['ARROZ'::character varying, 'PAPA'::character varying, 'ENSALADA'::character varying])::text[])))
);


ALTER TABLE public.guarniciones OWNER TO beckamdev;

--
-- Name: guarniciones_id_guarnicion_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.guarniciones ALTER COLUMN id_guarnicion ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guarniciones_id_guarnicion_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guarniciones_options; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.guarniciones_options (
    id_option bigint NOT NULL,
    id_guarnicion bigint NOT NULL,
    id_insumo bigint NOT NULL
);


ALTER TABLE public.guarniciones_options OWNER TO beckamdev;

--
-- Name: guarniciones_options_id_option_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.guarniciones_options ALTER COLUMN id_option ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guarniciones_options_id_option_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: guarniciones_selected; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.guarniciones_selected (
    id_guarnicion_selected bigint NOT NULL,
    id_option bigint NOT NULL,
    id_plato_selected bigint
);


ALTER TABLE public.guarniciones_selected OWNER TO beckamdev;

--
-- Name: guarniciones_selected_id_guarnicion_selected_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.guarniciones_selected ALTER COLUMN id_guarnicion_selected ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guarniciones_selected_id_guarnicion_selected_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: insumos; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.insumos (
    id_insumo bigint NOT NULL,
    name character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT insumos_type_check CHECK (((type)::text = ANY ((ARRAY['CARNE'::character varying, 'POLLO'::character varying, 'GUARNICION'::character varying])::text[])))
);


ALTER TABLE public.insumos OWNER TO beckamdev;

--
-- Name: insumos_id_insumo_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.insumos ALTER COLUMN id_insumo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.insumos_id_insumo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mesas; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.mesas (
    id_mesa bigint NOT NULL,
    numero_mesa integer NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT mesas_status_check CHECK (((status)::text = ANY ((ARRAY['LIBRE'::character varying, 'OCUPADA'::character varying, 'RESERVADA'::character varying, 'FUERA_DE_SERVICIO'::character varying])::text[])))
);


ALTER TABLE public.mesas OWNER TO beckamdev;

--
-- Name: mesas_id_mesa_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.mesas ALTER COLUMN id_mesa ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mesas_id_mesa_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: movements; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.movements (
    id_movement bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    description character varying(255) NOT NULL,
    id_type character varying(255),
    id_session bigint,
    CONSTRAINT movements_id_type_check CHECK (((id_type)::text = ANY ((ARRAY['INGRESO'::character varying, 'EGRESO'::character varying])::text[])))
);


ALTER TABLE public.movements OWNER TO beckamdev;

--
-- Name: movements_id_movement_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.movements ALTER COLUMN id_movement ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.movements_id_movement_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.orders (
    id_order bigint NOT NULL,
    fecha_order timestamp(6) without time zone,
    nombre_cliente character varying(255),
    modalidad character varying(255) NOT NULL,
    status smallint,
    total_amount numeric(38,2),
    id_employee bigint NOT NULL,
    CONSTRAINT orders_modalidad_check CHECK (((modalidad)::text = ANY ((ARRAY['PARA_MESA'::character varying, 'PARA_LLEVAR'::character varying])::text[]))),
    CONSTRAINT orders_status_check CHECK (((status >= 0) AND (status <= 6)))
);


ALTER TABLE public.orders OWNER TO beckamdev;

--
-- Name: orders_id_order_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.orders ALTER COLUMN id_order ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_order_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders_mesas; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.orders_mesas (
    id_order bigint NOT NULL,
    id_mesa bigint NOT NULL
);


ALTER TABLE public.orders_mesas OWNER TO beckamdev;

--
-- Name: payments; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.payments (
    id_payment bigint NOT NULL,
    amount numeric(38,2) NOT NULL,
    paid_at timestamp(6) without time zone NOT NULL,
    payment_method smallint NOT NULL,
    id_order bigint NOT NULL,
    id_session bigint NOT NULL,
    CONSTRAINT payments_payment_method_check CHECK (((payment_method >= 0) AND (payment_method <= 2)))
);


ALTER TABLE public.payments OWNER TO beckamdev;

--
-- Name: payments_id_payment_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.payments ALTER COLUMN id_payment ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_payment_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platos; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.platos (
    id_plato bigint NOT NULL,
    name character varying(255) NOT NULL,
    unit_price numeric(38,2) NOT NULL
);


ALTER TABLE public.platos OWNER TO beckamdev;

--
-- Name: platos_guarniciones; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.platos_guarniciones (
    id_plato bigint NOT NULL,
    id_guarnicion bigint NOT NULL
);


ALTER TABLE public.platos_guarniciones OWNER TO beckamdev;

--
-- Name: platos_id_plato_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.platos ALTER COLUMN id_plato ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platos_id_plato_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platos_insumos; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.platos_insumos (
    id_plato_insumo bigint NOT NULL,
    quantity integer NOT NULL,
    id_insumo bigint NOT NULL,
    id_plato bigint NOT NULL
);


ALTER TABLE public.platos_insumos OWNER TO beckamdev;

--
-- Name: platos_insumos_id_plato_insumo_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.platos_insumos ALTER COLUMN id_plato_insumo ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platos_insumos_id_plato_insumo_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: platos_selected; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.platos_selected (
    id_plato_selected bigint NOT NULL,
    status character varying(255) NOT NULL,
    subtotal numeric(38,2) NOT NULL,
    id_order bigint NOT NULL,
    id_plato bigint NOT NULL,
    CONSTRAINT platos_selected_status_check CHECK (((status)::text = ANY ((ARRAY['PENDIENTE'::character varying, 'PAGADO'::character varying, 'CANCELADO'::character varying, 'EN_MESA'::character varying, 'FINALIZADO'::character varying])::text[])))
);


ALTER TABLE public.platos_selected OWNER TO beckamdev;

--
-- Name: platos_selected_id_plato_selected_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.platos_selected ALTER COLUMN id_plato_selected ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.platos_selected_id_plato_selected_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    name character varying(255),
    CONSTRAINT roles_name_check CHECK (((name)::text = ANY ((ARRAY['ROLE_ADMIN'::character varying, 'ROLE_MESERO'::character varying, 'ROLE_COCINA'::character varying])::text[])))
);


ALTER TABLE public.roles OWNER TO beckamdev;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    password character varying(25) NOT NULL,
    username character varying(25) NOT NULL,
    id_employee bigint,
    id_role bigint
);


ALTER TABLE public.users OWNER TO beckamdev;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_week_config; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.work_week_config (
    id bigint NOT NULL,
    end_time time(0) without time zone NOT NULL,
    start_day character varying(255) NOT NULL,
    start_time time(0) without time zone NOT NULL,
    CONSTRAINT work_week_config_start_day_check CHECK (((start_day)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


ALTER TABLE public.work_week_config OWNER TO beckamdev;

--
-- Name: work_weeks; Type: TABLE; Schema: public; Owner: beckamdev
--

CREATE TABLE public.work_weeks (
    id_week bigint NOT NULL,
    end_date timestamp(6) without time zone NOT NULL,
    start_date timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT work_weeks_status_check CHECK (((status)::text = ANY ((ARRAY['ABIERTA'::character varying, 'CERRADA'::character varying])::text[])))
);


ALTER TABLE public.work_weeks OWNER TO beckamdev;

--
-- Name: work_weeks_id_week_seq; Type: SEQUENCE; Schema: public; Owner: beckamdev
--

ALTER TABLE public.work_weeks ALTER COLUMN id_week ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_weeks_id_week_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: agregados agregados_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.agregados
    ADD CONSTRAINT agregados_pkey PRIMARY KEY (id_agregado);


--
-- Name: agregados_selected agregados_selected_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.agregados_selected
    ADD CONSTRAINT agregados_selected_pkey PRIMARY KEY (id_agregado_selected);


--
-- Name: bebidas_options bebidas_options_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas_options
    ADD CONSTRAINT bebidas_options_pkey PRIMARY KEY (id_bebida_option);


--
-- Name: bebidas bebidas_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas
    ADD CONSTRAINT bebidas_pkey PRIMARY KEY (id_bebida);


--
-- Name: bebidas_selected bebidas_selected_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas_selected
    ADD CONSTRAINT bebidas_selected_pkey PRIMARY KEY (id_bebida_selected);


--
-- Name: bebidas_sizes bebidas_sizes_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas_sizes
    ADD CONSTRAINT bebidas_sizes_pkey PRIMARY KEY (id_bebida_size);


--
-- Name: cash_sessions cash_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.cash_sessions
    ADD CONSTRAINT cash_sessions_pkey PRIMARY KEY (id_session);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id_employee);


--
-- Name: guarniciones_options guarniciones_options_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.guarniciones_options
    ADD CONSTRAINT guarniciones_options_pkey PRIMARY KEY (id_option);


--
-- Name: guarniciones guarniciones_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.guarniciones
    ADD CONSTRAINT guarniciones_pkey PRIMARY KEY (id_guarnicion);


--
-- Name: guarniciones_selected guarniciones_selected_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.guarniciones_selected
    ADD CONSTRAINT guarniciones_selected_pkey PRIMARY KEY (id_guarnicion_selected);


--
-- Name: insumos insumos_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.insumos
    ADD CONSTRAINT insumos_pkey PRIMARY KEY (id_insumo);


--
-- Name: mesas mesas_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.mesas
    ADD CONSTRAINT mesas_pkey PRIMARY KEY (id_mesa);


--
-- Name: movements movements_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.movements
    ADD CONSTRAINT movements_pkey PRIMARY KEY (id_movement);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id_order);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id_payment);


--
-- Name: platos_insumos platos_insumos_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_insumos
    ADD CONSTRAINT platos_insumos_pkey PRIMARY KEY (id_plato_insumo);


--
-- Name: platos platos_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos
    ADD CONSTRAINT platos_pkey PRIMARY KEY (id_plato);


--
-- Name: platos_selected platos_selected_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_selected
    ADD CONSTRAINT platos_selected_pkey PRIMARY KEY (id_plato_selected);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: mesas ukft78dq09w3gjkq6qhsrb7dsts; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.mesas
    ADD CONSTRAINT ukft78dq09w3gjkq6qhsrb7dsts UNIQUE (numero_mesa);


--
-- Name: users ukitpfu3avhbnq43s58xiyhvibn; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukitpfu3avhbnq43s58xiyhvibn UNIQUE (id_employee);


--
-- Name: agregados uknxsm7s2ngi8svickbdnhgnhi9; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.agregados
    ADD CONSTRAINT uknxsm7s2ngi8svickbdnhgnhi9 UNIQUE (id_insumo);


--
-- Name: employees uko749373qjctaghb9gx23j7bm; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT uko749373qjctaghb9gx23j7bm UNIQUE (dni);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: work_week_config work_week_config_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.work_week_config
    ADD CONSTRAINT work_week_config_pkey PRIMARY KEY (id);


--
-- Name: work_weeks work_weeks_pkey; Type: CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.work_weeks
    ADD CONSTRAINT work_weeks_pkey PRIMARY KEY (id_week);


--
-- Name: guarniciones_selected fk1vjra124qq21x1aqeq3ie9w1t; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.guarniciones_selected
    ADD CONSTRAINT fk1vjra124qq21x1aqeq3ie9w1t FOREIGN KEY (id_option) REFERENCES public.guarniciones_options(id_option);


--
-- Name: bebidas_options fk2do6arpo6wsyeyilmt4sqoqwe; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas_options
    ADD CONSTRAINT fk2do6arpo6wsyeyilmt4sqoqwe FOREIGN KEY (id_bebida_size) REFERENCES public.bebidas_sizes(id_bebida_size);


--
-- Name: guarniciones_options fk2pfexcb2eurs31w670hpk4ysc; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.guarniciones_options
    ADD CONSTRAINT fk2pfexcb2eurs31w670hpk4ysc FOREIGN KEY (id_guarnicion) REFERENCES public.guarniciones(id_guarnicion);


--
-- Name: platos_guarniciones fk33wy1069as53l2vuv0ygdsyxx; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_guarniciones
    ADD CONSTRAINT fk33wy1069as53l2vuv0ygdsyxx FOREIGN KEY (id_guarnicion) REFERENCES public.guarniciones(id_guarnicion);


--
-- Name: agregados_selected fk4fcu6wj5txj3vmdm4nxifmuk4; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.agregados_selected
    ADD CONSTRAINT fk4fcu6wj5txj3vmdm4nxifmuk4 FOREIGN KEY (id_plato_selected) REFERENCES public.platos_selected(id_plato_selected);


--
-- Name: platos_guarniciones fk4m6c349fhq18r4iaoi883nb5f; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_guarniciones
    ADD CONSTRAINT fk4m6c349fhq18r4iaoi883nb5f FOREIGN KEY (id_plato) REFERENCES public.platos(id_plato);


--
-- Name: payments fk4o7chfmxqpa3aa4rpxnyxf21h; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk4o7chfmxqpa3aa4rpxnyxf21h FOREIGN KEY (id_session) REFERENCES public.cash_sessions(id_session);


--
-- Name: bebidas_selected fk647ty7dm2kjxrktcey1pqmvkf; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas_selected
    ADD CONSTRAINT fk647ty7dm2kjxrktcey1pqmvkf FOREIGN KEY (id_bebida_option) REFERENCES public.bebidas_options(id_bebida_option);


--
-- Name: users fk6846oiwlkn311d1oe679yt5po; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk6846oiwlkn311d1oe679yt5po FOREIGN KEY (id_employee) REFERENCES public.employees(id_employee);


--
-- Name: payments fkalvupkbf37ax1kxiayasm8k1x; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkalvupkbf37ax1kxiayasm8k1x FOREIGN KEY (id_order) REFERENCES public.orders(id_order);


--
-- Name: agregados_selected fkbkpigusx4tqr5x79r185afnp0; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.agregados_selected
    ADD CONSTRAINT fkbkpigusx4tqr5x79r185afnp0 FOREIGN KEY (id_agregado) REFERENCES public.agregados(id_agregado);


--
-- Name: platos_selected fkbll1exicrvb17gj1932nvccau; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_selected
    ADD CONSTRAINT fkbll1exicrvb17gj1932nvccau FOREIGN KEY (id_plato) REFERENCES public.platos(id_plato);


--
-- Name: guarniciones_options fkcjs9ib0v5slvb9ruykf55xhdn; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.guarniciones_options
    ADD CONSTRAINT fkcjs9ib0v5slvb9ruykf55xhdn FOREIGN KEY (id_insumo) REFERENCES public.insumos(id_insumo);


--
-- Name: platos_insumos fkf1muo00om31mkt75fghd6qs7u; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_insumos
    ADD CONSTRAINT fkf1muo00om31mkt75fghd6qs7u FOREIGN KEY (id_plato) REFERENCES public.platos(id_plato);


--
-- Name: orders fkfms71joqgt1gasxkeogetttdr; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkfms71joqgt1gasxkeogetttdr FOREIGN KEY (id_employee) REFERENCES public.employees(id_employee);


--
-- Name: guarniciones_selected fkfvd60tbv3mdyweo621pws5qyb; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.guarniciones_selected
    ADD CONSTRAINT fkfvd60tbv3mdyweo621pws5qyb FOREIGN KEY (id_plato_selected) REFERENCES public.platos_selected(id_plato_selected);


--
-- Name: orders_mesas fkgpjf2akhk1x4um3m8ri5htxlx; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.orders_mesas
    ADD CONSTRAINT fkgpjf2akhk1x4um3m8ri5htxlx FOREIGN KEY (id_mesa) REFERENCES public.mesas(id_mesa);


--
-- Name: orders_mesas fkieu6pt3v61dwmyf1cdkyibird; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.orders_mesas
    ADD CONSTRAINT fkieu6pt3v61dwmyf1cdkyibird FOREIGN KEY (id_order) REFERENCES public.orders(id_order);


--
-- Name: platos_insumos fklm6dcqdfubhqwtfc1y2lkvhkb; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_insumos
    ADD CONSTRAINT fklm6dcqdfubhqwtfc1y2lkvhkb FOREIGN KEY (id_insumo) REFERENCES public.insumos(id_insumo);


--
-- Name: bebidas_selected fkluvtb8u51caxc8frb54mbsk74; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas_selected
    ADD CONSTRAINT fkluvtb8u51caxc8frb54mbsk74 FOREIGN KEY (id_order) REFERENCES public.orders(id_order);


--
-- Name: bebidas_options fkmwlsflsnsk4bom7b8r9yxo5ic; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.bebidas_options
    ADD CONSTRAINT fkmwlsflsnsk4bom7b8r9yxo5ic FOREIGN KEY (id_bebida) REFERENCES public.bebidas(id_bebida);


--
-- Name: movements fkobh98ghrbtg5ccl3ib3l16wg4; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.movements
    ADD CONSTRAINT fkobh98ghrbtg5ccl3ib3l16wg4 FOREIGN KEY (id_session) REFERENCES public.cash_sessions(id_session);


--
-- Name: agregados fkpisjdw5wwa6fpnja2et6ygvro; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.agregados
    ADD CONSTRAINT fkpisjdw5wwa6fpnja2et6ygvro FOREIGN KEY (id_insumo) REFERENCES public.insumos(id_insumo);


--
-- Name: platos_selected fkrpbo3hfkuvgifiurhmd9n17ut; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.platos_selected
    ADD CONSTRAINT fkrpbo3hfkuvgifiurhmd9n17ut FOREIGN KEY (id_order) REFERENCES public.orders(id_order);


--
-- Name: cash_sessions fkt8i52a0smfg1qdanw9f4rmm3n; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.cash_sessions
    ADD CONSTRAINT fkt8i52a0smfg1qdanw9f4rmm3n FOREIGN KEY (id_week) REFERENCES public.work_weeks(id_week);


--
-- Name: users fkt92dgi4412ywy3u8tm9jwdya5; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fkt92dgi4412ywy3u8tm9jwdya5 FOREIGN KEY (id_role) REFERENCES public.roles(id);


--
-- Name: cash_sessions fktq1ywrf3iyk0tuyui4dpnrj99; Type: FK CONSTRAINT; Schema: public; Owner: beckamdev
--

ALTER TABLE ONLY public.cash_sessions
    ADD CONSTRAINT fktq1ywrf3iyk0tuyui4dpnrj99 FOREIGN KEY (id_employee) REFERENCES public.employees(id_employee);


--
-- PostgreSQL database dump complete
--

-- \unrestrict u3VVYyrS4te058acgXPbTWSv79geuZi5IQFtmwpjo3hCfce8kt8Vp1bYP5lFMcj

